on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      Comment: ${{ github.event.comment.body }}
    steps:
      - run: echo "comment - $Comment"
      - name: print body
        if: ${{ env.Comment == 'jenkins rebuild'}}
        run: echo "should trigger something"
