on: issue_comment

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: print body
        env:
          BODY: ${{ github.event.comment.body }}
        if: $BODY == 'deploy'
        run: echo "$BODY"
