on: issue_comment

jobs:
  pr_comment_rebuild:
    name: PR comment rebuild
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    env:
      Comment: ${{ github.event.comment.body }}
    steps:
      - run: echo "comment - $Comment"
      - name: print body
        if: ${{ env.Comment == 'jenkins rebuild'}}
        run: echo "should trigger something"
